package models

	import ( 
		"github.com/HerlambangHaryo/go-crud-simple/platform/database"  
		"time"  
		"gorm.io/gorm"
	)

	type FootballPatternFromCountry struct {
		gorm.Model
		ID                                       int       `gorm:"column:id;NOT NULL"`
		MatchWinnerHomeData                      int       `gorm:"column:match_winner_home_data"`
		MatchWinnerHomePerc                      float64   `gorm:"column:match_winner_home_perc"`
		MatchWinnerDrawData                      int       `gorm:"column:match_winner_draw_data"`
		MatchWinnerDrawPerc                      float64   `gorm:"column:match_winner_draw_perc"`
		MatchWinnerAwayData                      int       `gorm:"column:match_winner_away_data"`
		MatchWinnerAwayPerc                      float64   `gorm:"column:match_winner_away_perc"`
		HomeawayHomeData                         int       `gorm:"column:homeaway_home_data"`
		HomeawayHomePerc                         float64   `gorm:"column:homeaway_home_perc"`
		HomeawayAwayData                         int       `gorm:"column:homeaway_away_data"`
		HomeawayAwayPerc                         float64   `gorm:"column:homeaway_away_perc"`
		SecondHalfWinnerHomeData                 int       `gorm:"column:second_half_winner_home_data"`
		SecondHalfWinnerHomePerc                 float64   `gorm:"column:second_half_winner_home_perc"`
		SecondHalfWinnerDrawData                 int       `gorm:"column:second_half_winner_draw_data"`
		SecondHalfWinnerDrawPerc                 float64   `gorm:"column:second_half_winner_draw_perc"`
		SecondHalfWinnerAwayData                 int       `gorm:"column:second_half_winner_away_data"`
		SecondHalfWinnerAwayPerc                 float64   `gorm:"column:second_half_winner_away_perc"`
		AsianHandicapHomeMin65Data               int       `gorm:"column:asian_handicap_home_min_65_data"`
		AsianHandicapHomeMin65Perc               float64   `gorm:"column:asian_handicap_home_min_65_perc"`
		AsianHandicapAwayMin65Data               int       `gorm:"column:asian_handicap_away_min_65_data"`
		AsianHandicapAwayMin65Perc               float64   `gorm:"column:asian_handicap_away_min_65_perc"`
		AsianHandicapHomeMin6Data                int       `gorm:"column:asian_handicap_home_min_6_data"`
		AsianHandicapHomeMin6Perc                float64   `gorm:"column:asian_handicap_home_min_6_perc"`
		AsianHandicapAwayMin6Data                int       `gorm:"column:asian_handicap_away_min_6_data"`
		AsianHandicapAwayMin6Perc                float64   `gorm:"column:asian_handicap_away_min_6_perc"`
		AsianHandicapHomeMin55Data               int       `gorm:"column:asian_handicap_home_min_55_data"`
		AsianHandicapHomeMin55Perc               float64   `gorm:"column:asian_handicap_home_min_55_perc"`
		AsianHandicapAwayMin55Data               int       `gorm:"column:asian_handicap_away_min_55_data"`
		AsianHandicapAwayMin55Perc               float64   `gorm:"column:asian_handicap_away_min_55_perc"`
		AsianHandicapHomeMin5Data                int       `gorm:"column:asian_handicap_home_min_5_data"`
		AsianHandicapHomeMin5Perc                float64   `gorm:"column:asian_handicap_home_min_5_perc"`
		AsianHandicapAwayMin5Data                int       `gorm:"column:asian_handicap_away_min_5_data"`
		AsianHandicapAwayMin5Perc                float64   `gorm:"column:asian_handicap_away_min_5_perc"`
		AsianHandicapHomeMin45Data               int       `gorm:"column:asian_handicap_home_min_45_data"`
		AsianHandicapHomeMin45Perc               float64   `gorm:"column:asian_handicap_home_min_45_perc"`
		AsianHandicapAwayMin45Data               int       `gorm:"column:asian_handicap_away_min_45_data"`
		AsianHandicapAwayMin45Perc               float64   `gorm:"column:asian_handicap_away_min_45_perc"`
		AsianHandicapHomeMin4Data                int       `gorm:"column:asian_handicap_home_min_4_data"`
		AsianHandicapHomeMin4Perc                float64   `gorm:"column:asian_handicap_home_min_4_perc"`
		AsianHandicapAwayMin4Data                int       `gorm:"column:asian_handicap_away_min_4_data"`
		AsianHandicapAwayMin4Perc                float64   `gorm:"column:asian_handicap_away_min_4_perc"`
		AsianHandicapHomeMin35Data               int       `gorm:"column:asian_handicap_home_min_35_data"`
		AsianHandicapHomeMin35Perc               float64   `gorm:"column:asian_handicap_home_min_35_perc"`
		AsianHandicapAwayMin35Data               int       `gorm:"column:asian_handicap_away_min_35_data"`
		AsianHandicapAwayMin35Perc               float64   `gorm:"column:asian_handicap_away_min_35_perc"`
		AsianHandicapHomeMin3Data                int       `gorm:"column:asian_handicap_home_min_3_data"`
		AsianHandicapHomeMin3Perc                float64   `gorm:"column:asian_handicap_home_min_3_perc"`
		AsianHandicapAwayMin3Data                int       `gorm:"column:asian_handicap_away_min_3_data"`
		AsianHandicapAwayMin3Perc                float64   `gorm:"column:asian_handicap_away_min_3_perc"`
		AsianHandicapHomeMin25Data               int       `gorm:"column:asian_handicap_home_min_25_data"`
		AsianHandicapHomeMin25Perc               float64   `gorm:"column:asian_handicap_home_min_25_perc"`
		AsianHandicapAwayMin25Data               int       `gorm:"column:asian_handicap_away_min_25_data"`
		AsianHandicapAwayMin25Perc               float64   `gorm:"column:asian_handicap_away_min_25_perc"`
		AsianHandicapHomeMin2Data                int       `gorm:"column:asian_handicap_home_min_2_data"`
		AsianHandicapHomeMin2Perc                float64   `gorm:"column:asian_handicap_home_min_2_perc"`
		AsianHandicapAwayMin2Data                int       `gorm:"column:asian_handicap_away_min_2_data"`
		AsianHandicapAwayMin2Perc                float64   `gorm:"column:asian_handicap_away_min_2_perc"`
		AsianHandicapHomeMin15Data               int       `gorm:"column:asian_handicap_home_min_15_data"`
		AsianHandicapHomeMin15Perc               float64   `gorm:"column:asian_handicap_home_min_15_perc"`
		AsianHandicapAwayMin15Data               int       `gorm:"column:asian_handicap_away_min_15_data"`
		AsianHandicapAwayMin15Perc               float64   `gorm:"column:asian_handicap_away_min_15_perc"`
		AsianHandicapHomeMin1Data                int       `gorm:"column:asian_handicap_home_min_1_data"`
		AsianHandicapHomeMin1Perc                float64   `gorm:"column:asian_handicap_home_min_1_perc"`
		AsianHandicapAwayMin1Data                int       `gorm:"column:asian_handicap_away_min_1_data"`
		AsianHandicapAwayMin1Perc                float64   `gorm:"column:asian_handicap_away_min_1_perc"`
		AsianHandicapHomeMin05Data               int       `gorm:"column:asian_handicap_home_min_05_data"`
		AsianHandicapHomeMin05Perc               float64   `gorm:"column:asian_handicap_home_min_05_perc"`
		AsianHandicapAwayMin05Data               int       `gorm:"column:asian_handicap_away_min_05_data"`
		AsianHandicapAwayMin05Perc               float64   `gorm:"column:asian_handicap_away_min_05_perc"`
		AsianHandicapHomePlus0Data               int       `gorm:"column:asian_handicap_home_plus_0_data"`
		AsianHandicapHomePlus0Perc               float64   `gorm:"column:asian_handicap_home_plus_0_perc"`
		AsianHandicapAwayPlus0Data               int       `gorm:"column:asian_handicap_away_plus_0_data"`
		AsianHandicapAwayPlus0Perc               float64   `gorm:"column:asian_handicap_away_plus_0_perc"`
		AsianHandicapHomePlus05Data              int       `gorm:"column:asian_handicap_home_plus_05_data"`
		AsianHandicapHomePlus05Perc              float64   `gorm:"column:asian_handicap_home_plus_05_perc"`
		AsianHandicapAwayPlus05Data              int       `gorm:"column:asian_handicap_away_plus_05_data"`
		AsianHandicapAwayPlus05Perc              float64   `gorm:"column:asian_handicap_away_plus_05_perc"`
		AsianHandicapHomePlus1Data               int       `gorm:"column:asian_handicap_home_plus_1_data"`
		AsianHandicapHomePlus1Perc               float64   `gorm:"column:asian_handicap_home_plus_1_perc"`
		AsianHandicapAwayPlus1Data               int       `gorm:"column:asian_handicap_away_plus_1_data"`
		AsianHandicapAwayPlus1Perc               float64   `gorm:"column:asian_handicap_away_plus_1_perc"`
		AsianHandicapHomePlus15Data              int       `gorm:"column:asian_handicap_home_plus_15_data"`
		AsianHandicapHomePlus15Perc              float64   `gorm:"column:asian_handicap_home_plus_15_perc"`
		AsianHandicapAwayPlus15Data              int       `gorm:"column:asian_handicap_away_plus_15_data"`
		AsianHandicapAwayPlus15Perc              float64   `gorm:"column:asian_handicap_away_plus_15_perc"`
		AsianHandicapHomePlus2Data               int       `gorm:"column:asian_handicap_home_plus_2_data"`
		AsianHandicapHomePlus2Perc               float64   `gorm:"column:asian_handicap_home_plus_2_perc"`
		AsianHandicapAwayPlus2Data               int       `gorm:"column:asian_handicap_away_plus_2_data"`
		AsianHandicapAwayPlus2Perc               float64   `gorm:"column:asian_handicap_away_plus_2_perc"`
		AsianHandicapHomePlus25Data              int       `gorm:"column:asian_handicap_home_plus_25_data"`
		AsianHandicapHomePlus25Perc              float64   `gorm:"column:asian_handicap_home_plus_25_perc"`
		AsianHandicapAwayPlus25Data              int       `gorm:"column:asian_handicap_away_plus_25_data"`
		AsianHandicapAwayPlus25Perc              float64   `gorm:"column:asian_handicap_away_plus_25_perc"`
		AsianHandicapHomePlus3Data               int       `gorm:"column:asian_handicap_home_plus_3_data"`
		AsianHandicapHomePlus3Perc               float64   `gorm:"column:asian_handicap_home_plus_3_perc"`
		AsianHandicapAwayPlus3Data               int       `gorm:"column:asian_handicap_away_plus_3_data"`
		AsianHandicapAwayPlus3Perc               float64   `gorm:"column:asian_handicap_away_plus_3_perc"`
		AsianHandicapHomePlus35Data              int       `gorm:"column:asian_handicap_home_plus_35_data"`
		AsianHandicapHomePlus35Perc              float64   `gorm:"column:asian_handicap_home_plus_35_perc"`
		AsianHandicapAwayPlus35Data              int       `gorm:"column:asian_handicap_away_plus_35_data"`
		AsianHandicapAwayPlus35Perc              float64   `gorm:"column:asian_handicap_away_plus_35_perc"`
		AsianHandicapHomePlus4Data               int       `gorm:"column:asian_handicap_home_plus_4_data"`
		AsianHandicapHomePlus4Perc               float64   `gorm:"column:asian_handicap_home_plus_4_perc"`
		AsianHandicapAwayPlus4Data               int       `gorm:"column:asian_handicap_away_plus_4_data"`
		AsianHandicapAwayPlus4Perc               float64   `gorm:"column:asian_handicap_away_plus_4_perc"`
		AsianHandicapHomePlus45Data              int       `gorm:"column:asian_handicap_home_plus_45_data"`
		AsianHandicapHomePlus45Perc              float64   `gorm:"column:asian_handicap_home_plus_45_perc"`
		AsianHandicapAwayPlus45Data              int       `gorm:"column:asian_handicap_away_plus_45_data"`
		AsianHandicapAwayPlus45Perc              float64   `gorm:"column:asian_handicap_away_plus_45_perc"`
		AsianHandicapHomePlus5Data               int       `gorm:"column:asian_handicap_home_plus_5_data"`
		AsianHandicapHomePlus5Perc               float64   `gorm:"column:asian_handicap_home_plus_5_perc"`
		AsianHandicapAwayPlus5Data               int       `gorm:"column:asian_handicap_away_plus_5_data"`
		AsianHandicapAwayPlus5Perc               float64   `gorm:"column:asian_handicap_away_plus_5_perc"`
		AsianHandicapHomePlus55Data              int       `gorm:"column:asian_handicap_home_plus_55_data"`
		AsianHandicapHomePlus55Perc              float64   `gorm:"column:asian_handicap_home_plus_55_perc"`
		AsianHandicapAwayPlus55Data              int       `gorm:"column:asian_handicap_away_plus_55_data"`
		AsianHandicapAwayPlus55Perc              float64   `gorm:"column:asian_handicap_away_plus_55_perc"`
		AsianHandicapHomePlus6Data               int       `gorm:"column:asian_handicap_home_plus_6_data"`
		AsianHandicapHomePlus6Perc               float64   `gorm:"column:asian_handicap_home_plus_6_perc"`
		AsianHandicapAwayPlus6Data               int       `gorm:"column:asian_handicap_away_plus_6_data"`
		AsianHandicapAwayPlus6Perc               float64   `gorm:"column:asian_handicap_away_plus_6_perc"`
		AsianHandicapHomePlus65Data              int       `gorm:"column:asian_handicap_home_plus_65_data"`
		AsianHandicapHomePlus65Perc              float64   `gorm:"column:asian_handicap_home_plus_65_perc"`
		AsianHandicapAwayPlus65Data              int       `gorm:"column:asian_handicap_away_plus_65_data"`
		AsianHandicapAwayPlus65Perc              float64   `gorm:"column:asian_handicap_away_plus_65_perc"`
		GoalsOverunderOver05Data                 int       `gorm:"column:goals_overunder_over_05_data"`
		GoalsOverunderOver05Perc                 float64   `gorm:"column:goals_overunder_over_05_perc"`
		GoalsOverunderUnder05Data                int       `gorm:"column:goals_overunder_under_05_data"`
		GoalsOverunderUnder05Perc                float64   `gorm:"column:goals_overunder_under_05_perc"`
		GoalsOverunderOver10Data                 int       `gorm:"column:goals_overunder_over_10_data"`
		GoalsOverunderOver10Perc                 float64   `gorm:"column:goals_overunder_over_10_perc"`
		GoalsOverunderUnder10Data                int       `gorm:"column:goals_overunder_under_10_data"`
		GoalsOverunderUnder10Perc                float64   `gorm:"column:goals_overunder_under_10_perc"`
		GoalsOverunderOver15Data                 int       `gorm:"column:goals_overunder_over_15_data"`
		GoalsOverunderOver15Perc                 float64   `gorm:"column:goals_overunder_over_15_perc"`
		GoalsOverunderUnder15Data                int       `gorm:"column:goals_overunder_under_15_data"`
		GoalsOverunderUnder15Perc                float64   `gorm:"column:goals_overunder_under_15_perc"`
		GoalsOverunderOver20Data                 int       `gorm:"column:goals_overunder_over_20_data"`
		GoalsOverunderOver20Perc                 float64   `gorm:"column:goals_overunder_over_20_perc"`
		GoalsOverunderUnder20Data                int       `gorm:"column:goals_overunder_under_20_data"`
		GoalsOverunderUnder20Perc                float64   `gorm:"column:goals_overunder_under_20_perc"`
		GoalsOverunderOver25Data                 int       `gorm:"column:goals_overunder_over_25_data"`
		GoalsOverunderOver25Perc                 float64   `gorm:"column:goals_overunder_over_25_perc"`
		GoalsOverunderUnder25Data                int       `gorm:"column:goals_overunder_under_25_data"`
		GoalsOverunderUnder25Perc                float64   `gorm:"column:goals_overunder_under_25_perc"`
		GoalsOverunderOver30Data                 int       `gorm:"column:goals_overunder_over_30_data"`
		GoalsOverunderOver30Perc                 float64   `gorm:"column:goals_overunder_over_30_perc"`
		GoalsOverunderUnder30Data                int       `gorm:"column:goals_overunder_under_30_data"`
		GoalsOverunderUnder30Perc                float64   `gorm:"column:goals_overunder_under_30_perc"`
		GoalsOverunderOver35Data                 int       `gorm:"column:goals_overunder_over_35_data"`
		GoalsOverunderOver35Perc                 float64   `gorm:"column:goals_overunder_over_35_perc"`
		GoalsOverunderUnder35Data                int       `gorm:"column:goals_overunder_under_35_data"`
		GoalsOverunderUnder35Perc                float64   `gorm:"column:goals_overunder_under_35_perc"`
		GoalsOverunderOver40Data                 int       `gorm:"column:goals_overunder_over_40_data"`
		GoalsOverunderOver40Perc                 float64   `gorm:"column:goals_overunder_over_40_perc"`
		GoalsOverunderUnder40Data                int       `gorm:"column:goals_overunder_under_40_data"`
		GoalsOverunderUnder40Perc                float64   `gorm:"column:goals_overunder_under_40_perc"`
		GoalsOverunderOver45Data                 int       `gorm:"column:goals_overunder_over_45_data"`
		GoalsOverunderOver45Perc                 float64   `gorm:"column:goals_overunder_over_45_perc"`
		GoalsOverunderUnder45Data                int       `gorm:"column:goals_overunder_under_45_data"`
		GoalsOverunderUnder45Perc                float64   `gorm:"column:goals_overunder_under_45_perc"`
		GoalsOverunderOver50Data                 int       `gorm:"column:goals_overunder_over_50_data"`
		GoalsOverunderOver50Perc                 float64   `gorm:"column:goals_overunder_over_50_perc"`
		GoalsOverunderUnder50Data                int       `gorm:"column:goals_overunder_under_50_data"`
		GoalsOverunderUnder50Perc                float64   `gorm:"column:goals_overunder_under_50_perc"`
		GoalsOverunderOver55Data                 int       `gorm:"column:goals_overunder_over_55_data"`
		GoalsOverunderOver55Perc                 float64   `gorm:"column:goals_overunder_over_55_perc"`
		GoalsOverunderUnder55Data                int       `gorm:"column:goals_overunder_under_55_data"`
		GoalsOverunderUnder55Perc                float64   `gorm:"column:goals_overunder_under_55_perc"`
		GoalsOverunderOver60Data                 int       `gorm:"column:goals_overunder_over_60_data"`
		GoalsOverunderOver60Perc                 float64   `gorm:"column:goals_overunder_over_60_perc"`
		GoalsOverunderUnder60Data                int       `gorm:"column:goals_overunder_under_60_data"`
		GoalsOverunderUnder60Perc                float64   `gorm:"column:goals_overunder_under_60_perc"`
		GoalsOverunderOver65Data                 int       `gorm:"column:goals_overunder_over_65_data"`
		GoalsOverunderOver65Perc                 float64   `gorm:"column:goals_overunder_over_65_perc"`
		GoalsOverunderUnder65Data                int       `gorm:"column:goals_overunder_under_65_data"`
		GoalsOverunderUnder65Perc                float64   `gorm:"column:goals_overunder_under_65_perc"`
		GoalsOverunderOver70Data                 int       `gorm:"column:goals_overunder_over_70_data"`
		GoalsOverunderOver70Perc                 float64   `gorm:"column:goals_overunder_over_70_perc"`
		GoalsOverunderUnder70Data                int       `gorm:"column:goals_overunder_under_70_data"`
		GoalsOverunderUnder70Perc                float64   `gorm:"column:goals_overunder_under_70_perc"`
		GoalsOverunderOver75Data                 int       `gorm:"column:goals_overunder_over_75_data"`
		GoalsOverunderOver75Perc                 float64   `gorm:"column:goals_overunder_over_75_perc"`
		GoalsOverunderUnder75Data                int       `gorm:"column:goals_overunder_under_75_data"`
		GoalsOverunderUnder75Perc                float64   `gorm:"column:goals_overunder_under_75_perc"`
		GoalsOverunderOver85Data                 int       `gorm:"column:goals_overunder_over_85_data"`
		GoalsOverunderOver85Perc                 float64   `gorm:"column:goals_overunder_over_85_perc"`
		GoalsOverunderUnder85Data                int       `gorm:"column:goals_overunder_under_85_data"`
		GoalsOverunderUnder85Perc                float64   `gorm:"column:goals_overunder_under_85_perc"`
		GoalsOverunderOver95Data                 int       `gorm:"column:goals_overunder_over_95_data"`
		GoalsOverunderOver95Perc                 float64   `gorm:"column:goals_overunder_over_95_perc"`
		GoalsOverunderUnder95Data                int       `gorm:"column:goals_overunder_under_95_data"`
		GoalsOverunderUnder95Perc                float64   `gorm:"column:goals_overunder_under_95_perc"`
		GoalsOverunderFirstHalfOver05Data        int       `gorm:"column:goals_overunder_first_half_over_05_data"`
		GoalsOverunderFirstHalfOver05Perc        float64   `gorm:"column:goals_overunder_first_half_over_05_perc"`
		GoalsOverunderFirstHalfUnder05Data       int       `gorm:"column:goals_overunder_first_half_under_05_data"`
		GoalsOverunderFirstHalfUnder05Perc       float64   `gorm:"column:goals_overunder_first_half_under_05_perc"`
		GoalsOverunderFirstHalfOver10Data        int       `gorm:"column:goals_overunder_first_half_over_10_data"`
		GoalsOverunderFirstHalfOver10Perc        float64   `gorm:"column:goals_overunder_first_half_over_10_perc"`
		GoalsOverunderFirstHalfUnder10Data       int       `gorm:"column:goals_overunder_first_half_under_10_data"`
		GoalsOverunderFirstHalfUnder10Perc       float64   `gorm:"column:goals_overunder_first_half_under_10_perc"`
		GoalsOverunderFirstHalfOver15Data        int       `gorm:"column:goals_overunder_first_half_over_15_data"`
		GoalsOverunderFirstHalfOver15Perc        float64   `gorm:"column:goals_overunder_first_half_over_15_perc"`
		GoalsOverunderFirstHalfUnder15Data       int       `gorm:"column:goals_overunder_first_half_under_15_data"`
		GoalsOverunderFirstHalfUnder15Perc       float64   `gorm:"column:goals_overunder_first_half_under_15_perc"`
		GoalsOverunderFirstHalfOver20Data        int       `gorm:"column:goals_overunder_first_half_over_20_data"`
		GoalsOverunderFirstHalfOver20Perc        float64   `gorm:"column:goals_overunder_first_half_over_20_perc"`
		GoalsOverunderFirstHalfUnder20Data       int       `gorm:"column:goals_overunder_first_half_under_20_data"`
		GoalsOverunderFirstHalfUnder20Perc       float64   `gorm:"column:goals_overunder_first_half_under_20_perc"`
		GoalsOverunderFirstHalfOver25Data        int       `gorm:"column:goals_overunder_first_half_over_25_data"`
		GoalsOverunderFirstHalfOver25Perc        float64   `gorm:"column:goals_overunder_first_half_over_25_perc"`
		GoalsOverunderFirstHalfUnder25Data       int       `gorm:"column:goals_overunder_first_half_under_25_data"`
		GoalsOverunderFirstHalfUnder25Perc       float64   `gorm:"column:goals_overunder_first_half_under_25_perc"`
		GoalsOverunderFirstHalfOver30Data        int       `gorm:"column:goals_overunder_first_half_over_30_data"`
		GoalsOverunderFirstHalfOver30Perc        float64   `gorm:"column:goals_overunder_first_half_over_30_perc"`
		GoalsOverunderFirstHalfUnder30Data       int       `gorm:"column:goals_overunder_first_half_under_30_data"`
		GoalsOverunderFirstHalfUnder30Perc       float64   `gorm:"column:goals_overunder_first_half_under_30_perc"`
		GoalsOverunderFirstHalfOver35Data        int       `gorm:"column:goals_overunder_first_half_over_35_data"`
		GoalsOverunderFirstHalfOver35Perc        float64   `gorm:"column:goals_overunder_first_half_over_35_perc"`
		GoalsOverunderFirstHalfUnder35Data       int       `gorm:"column:goals_overunder_first_half_under_35_data"`
		GoalsOverunderFirstHalfUnder35Perc       float64   `gorm:"column:goals_overunder_first_half_under_35_perc"`
		HtftDoubleHomeHomeData                   int       `gorm:"column:htft_double_home_home_data"`
		HtftDoubleHomeHomePerc                   float64   `gorm:"column:htft_double_home_home_perc"`
		HtftDoubleHomeDrawData                   int       `gorm:"column:htft_double_home_draw_data"`
		HtftDoubleHomeDrawPerc                   float64   `gorm:"column:htft_double_home_draw_perc"`
		HtftDoubleHomeAwayData                   int       `gorm:"column:htft_double_home_away_data"`
		HtftDoubleHomeAwayPerc                   float64   `gorm:"column:htft_double_home_away_perc"`
		HtftDoubleDrawHomeData                   int       `gorm:"column:htft_double_draw_home_data"`
		HtftDoubleDrawHomePerc                   float64   `gorm:"column:htft_double_draw_home_perc"`
		HtftDoubleDrawDrawData                   int       `gorm:"column:htft_double_draw_draw_data"`
		HtftDoubleDrawDrawPerc                   float64   `gorm:"column:htft_double_draw_draw_perc"`
		HtftDoubleDrawAwayData                   int       `gorm:"column:htft_double_draw_away_data"`
		HtftDoubleDrawAwayPerc                   float64   `gorm:"column:htft_double_draw_away_perc"`
		HtftDoubleAwayHomeData                   int       `gorm:"column:htft_double_away_home_data"`
		HtftDoubleAwayHomePerc                   float64   `gorm:"column:htft_double_away_home_perc"`
		HtftDoubleAwayDrawData                   int       `gorm:"column:htft_double_away_draw_data"`
		HtftDoubleAwayDrawPerc                   float64   `gorm:"column:htft_double_away_draw_perc"`
		HtftDoubleAwayAwayData                   int       `gorm:"column:htft_double_away_away_data"`
		HtftDoubleAwayAwayPerc                   float64   `gorm:"column:htft_double_away_away_perc"`
		BothTeamsScoreYesData                    int       `gorm:"column:both_teams_score_yes_data"`
		BothTeamsScoreYesPerc                    float64   `gorm:"column:both_teams_score_yes_perc"`
		BothTeamsScoreNoData                     int       `gorm:"column:both_teams_score_no_data"`
		BothTeamsScoreNoPerc                     float64   `gorm:"column:both_teams_score_no_perc"`
		HighestScoringHalfFirstData              int       `gorm:"column:highest_scoring_half_first_data"`
		HighestScoringHalfFirstPerc              float64   `gorm:"column:highest_scoring_half_first_perc"`
		HighestScoringHalfDrawData               int       `gorm:"column:highest_scoring_half_draw_data"`
		HighestScoringHalfDrawPerc               float64   `gorm:"column:highest_scoring_half_draw_perc"`
		HighestScoringHalfSecondData             int       `gorm:"column:highest_scoring_half_second_data"`
		HighestScoringHalfSecondPerc             float64   `gorm:"column:highest_scoring_half_second_perc"`
		DoubleChanceHomeDrawData                 int       `gorm:"column:double_chance_home_draw_data"`
		DoubleChanceHomeDrawPerc                 float64   `gorm:"column:double_chance_home_draw_perc"`
		DoubleChanceHomeAwayData                 int       `gorm:"column:double_chance_home_away_data"`
		DoubleChanceHomeAwayPerc                 float64   `gorm:"column:double_chance_home_away_perc"`
		DoubleChanceDrawAwayData                 int       `gorm:"column:double_chance_draw_away_data"`
		DoubleChanceDrawAwayPerc                 float64   `gorm:"column:double_chance_draw_away_perc"`
		FirstHalfWinnerHomeData                  int       `gorm:"column:first_half_winner_home_data"`
		FirstHalfWinnerHomePerc                  float64   `gorm:"column:first_half_winner_home_perc"`
		FirstHalfWinnerDrawData                  int       `gorm:"column:first_half_winner_draw_data"`
		FirstHalfWinnerDrawPerc                  float64   `gorm:"column:first_half_winner_draw_perc"`
		FirstHalfWinnerAwayData                  int       `gorm:"column:first_half_winner_away_data"`
		FirstHalfWinnerAwayPerc                  float64   `gorm:"column:first_half_winner_away_perc"`
		TotalHomeOver15Data                      int       `gorm:"column:total_home_over_15_data"`
		TotalHomeOver15Perc                      float64   `gorm:"column:total_home_over_15_perc"`
		TotalHomeUnder15Data                     int       `gorm:"column:total_home_under_15_data"`
		TotalHomeUnder15Perc                     float64   `gorm:"column:total_home_under_15_perc"`
		TotalHomeOver25Data                      int       `gorm:"column:total_home_over_25_data"`
		TotalHomeOver25Perc                      float64   `gorm:"column:total_home_over_25_perc"`
		TotalHomeUnder25Data                     int       `gorm:"column:total_home_under_25_data"`
		TotalHomeUnder25Perc                     float64   `gorm:"column:total_home_under_25_perc"`
		TotalHomeOver35Data                      int       `gorm:"column:total_home_over_35_data"`
		TotalHomeOver35Perc                      float64   `gorm:"column:total_home_over_35_perc"`
		TotalHomeUnder35Data                     int       `gorm:"column:total_home_under_35_data"`
		TotalHomeUnder35Perc                     float64   `gorm:"column:total_home_under_35_perc"`
		TotalHomeOver45Data                      int       `gorm:"column:total_home_over_45_data"`
		TotalHomeOver45Perc                      float64   `gorm:"column:total_home_over_45_perc"`
		TotalHomeUnder45Data                     int       `gorm:"column:total_home_under_45_data"`
		TotalHomeUnder45Perc                     float64   `gorm:"column:total_home_under_45_perc"`
		TotalHomeOver55Data                      int       `gorm:"column:total_home_over_55_data"`
		TotalHomeOver55Perc                      float64   `gorm:"column:total_home_over_55_perc"`
		TotalHomeUnder55Data                     int       `gorm:"column:total_home_under_55_data"`
		TotalHomeUnder55Perc                     float64   `gorm:"column:total_home_under_55_perc"`
		TotalHomeOver65Data                      int       `gorm:"column:total_home_over_65_data"`
		TotalHomeOver65Perc                      float64   `gorm:"column:total_home_over_65_perc"`
		TotalHomeUnder65Data                     int       `gorm:"column:total_home_under_65_data"`
		TotalHomeUnder65Perc                     float64   `gorm:"column:total_home_under_65_perc"`
		TotalAwayOver15Data                      int       `gorm:"column:total_away_over_15_data"`
		TotalAwayOver15Perc                      float64   `gorm:"column:total_away_over_15_perc"`
		TotalAwayUnder15Data                     int       `gorm:"column:total_away_under_15_data"`
		TotalAwayUnder15Perc                     float64   `gorm:"column:total_away_under_15_perc"`
		TotalAwayOver25Data                      int       `gorm:"column:total_away_over_25_data"`
		TotalAwayOver25Perc                      float64   `gorm:"column:total_away_over_25_perc"`
		TotalAwayUnder25Data                     int       `gorm:"column:total_away_under_25_data"`
		TotalAwayUnder25Perc                     float64   `gorm:"column:total_away_under_25_perc"`
		TotalAwayOver35Data                      int       `gorm:"column:total_away_over_35_data"`
		TotalAwayOver35Perc                      float64   `gorm:"column:total_away_over_35_perc"`
		TotalAwayUnder35Data                     int       `gorm:"column:total_away_under_35_data"`
		TotalAwayUnder35Perc                     float64   `gorm:"column:total_away_under_35_perc"`
		TotalAwayOver45Data                      int       `gorm:"column:total_away_over_45_data"`
		TotalAwayOver45Perc                      float64   `gorm:"column:total_away_over_45_perc"`
		TotalAwayUnder45Data                     int       `gorm:"column:total_away_under_45_data"`
		TotalAwayUnder45Perc                     float64   `gorm:"column:total_away_under_45_perc"`
		TotalAwayOver55Data                      int       `gorm:"column:total_away_over_55_data"`
		TotalAwayOver55Perc                      float64   `gorm:"column:total_away_over_55_perc"`
		TotalAwayUnder55Data                     int       `gorm:"column:total_away_under_55_data"`
		TotalAwayUnder55Perc                     float64   `gorm:"column:total_away_under_55_perc"`
		TotalAwayOver65Data                      int       `gorm:"column:total_away_over_65_data"`
		TotalAwayOver65Perc                      float64   `gorm:"column:total_away_over_65_perc"`
		TotalAwayUnder65Data                     int       `gorm:"column:total_away_under_65_data"`
		TotalAwayUnder65Perc                     float64   `gorm:"column:total_away_under_65_perc"`
		AsianHandicapFirstHalfHomeMin15Data      int       `gorm:"column:asian_handicap_first_half_home_min_15_data"`
		AsianHandicapFirstHalfHomeMin15Perc      float64   `gorm:"column:asian_handicap_first_half_home_min_15_perc"`
		AsianHandicapFirstHalfAwayMin15Data      int       `gorm:"column:asian_handicap_first_half_away_min_15_data"`
		AsianHandicapFirstHalfAwayMin15Perc      float64   `gorm:"column:asian_handicap_first_half_away_min_15_perc"`
		AsianHandicapFirstHalfHomeMin1Data       int       `gorm:"column:asian_handicap_first_half_home_min_1_data"`
		AsianHandicapFirstHalfHomeMin1Perc       float64   `gorm:"column:asian_handicap_first_half_home_min_1_perc"`
		AsianHandicapFirstHalfAwayMin1Data       int       `gorm:"column:asian_handicap_first_half_away_min_1_data"`
		AsianHandicapFirstHalfAwayMin1Perc       float64   `gorm:"column:asian_handicap_first_half_away_min_1_perc"`
		AsianHandicapFirstHalfHomeMin05Data      int       `gorm:"column:asian_handicap_first_half_home_min_05_data"`
		AsianHandicapFirstHalfHomeMin05Perc      float64   `gorm:"column:asian_handicap_first_half_home_min_05_perc"`
		AsianHandicapFirstHalfAwayMin05Data      int       `gorm:"column:asian_handicap_first_half_away_min_05_data"`
		AsianHandicapFirstHalfAwayMin05Perc      float64   `gorm:"column:asian_handicap_first_half_away_min_05_perc"`
		AsianHandicapFirstHalfHomePlus0Data      int       `gorm:"column:asian_handicap_first_half_home_plus_0_data"`
		AsianHandicapFirstHalfHomePlus0Perc      float64   `gorm:"column:asian_handicap_first_half_home_plus_0_perc"`
		AsianHandicapFirstHalfAwayPlus0Data      int       `gorm:"column:asian_handicap_first_half_away_plus_0_data"`
		AsianHandicapFirstHalfAwayPlus0Perc      float64   `gorm:"column:asian_handicap_first_half_away_plus_0_perc"`
		AsianHandicapFirstHalfHomePlus05Data     int       `gorm:"column:asian_handicap_first_half_home_plus_05_data"`
		AsianHandicapFirstHalfHomePlus05Perc     float64   `gorm:"column:asian_handicap_first_half_home_plus_05_perc"`
		AsianHandicapFirstHalfAwayPlus05Data     int       `gorm:"column:asian_handicap_first_half_away_plus_05_data"`
		AsianHandicapFirstHalfAwayPlus05Perc     float64   `gorm:"column:asian_handicap_first_half_away_plus_05_perc"`
		AsianHandicapFirstHalfHomePlus1Data      int       `gorm:"column:asian_handicap_first_half_home_plus_1_data"`
		AsianHandicapFirstHalfHomePlus1Perc      float64   `gorm:"column:asian_handicap_first_half_home_plus_1_perc"`
		AsianHandicapFirstHalfAwayPlus1Data      int       `gorm:"column:asian_handicap_first_half_away_plus_1_data"`
		AsianHandicapFirstHalfAwayPlus1Perc      float64   `gorm:"column:asian_handicap_first_half_away_plus_1_perc"`
		AsianHandicapFirstHalfHomePlus15Data     int       `gorm:"column:asian_handicap_first_half_home_plus_15_data"`
		AsianHandicapFirstHalfHomePlus15Perc     float64   `gorm:"column:asian_handicap_first_half_home_plus_15_perc"`
		AsianHandicapFirstHalfAwayPlus15Data     int       `gorm:"column:asian_handicap_first_half_away_plus_15_data"`
		AsianHandicapFirstHalfAwayPlus15Perc     float64   `gorm:"column:asian_handicap_first_half_away_plus_15_perc"`
		DoubleChanceFirstHalfHomeDrawData        int       `gorm:"column:double_chance__first_half_home_draw_data"`
		DoubleChanceFirstHalfHomeDrawPerc        float64   `gorm:"column:double_chance__first_half_home_draw_perc"`
		DoubleChanceFirstHalfHomeAwayData        int       `gorm:"column:double_chance__first_half_home_away_data"`
		DoubleChanceFirstHalfHomeAwayPerc        float64   `gorm:"column:double_chance__first_half_home_away_perc"`
		DoubleChanceFirstHalfDrawAwayData        int       `gorm:"column:double_chance__first_half_draw_away_data"`
		DoubleChanceFirstHalfDrawAwayPerc        float64   `gorm:"column:double_chance__first_half_draw_away_perc"`
		OddevenOddData                           int       `gorm:"column:oddeven_odd_data"`
		OddevenOddPerc                           float64   `gorm:"column:oddeven_odd_perc"`
		OddevenEvenData                          int       `gorm:"column:oddeven_even_data"`
		OddevenEvenPerc                          float64   `gorm:"column:oddeven_even_perc"`
		ResultsBothTeamsScoreHomeYesData         int       `gorm:"column:results_both_teams_score_home_yes_data"`
		ResultsBothTeamsScoreHomeYesPerc         float64   `gorm:"column:results_both_teams_score_home_yes_perc"`
		ResultsBothTeamsScoreDrawYesData         int       `gorm:"column:results_both_teams_score_draw_yes_data"`
		ResultsBothTeamsScoreDrawYesPerc         float64   `gorm:"column:results_both_teams_score_draw_yes_perc"`
		ResultsBothTeamsScoreAwayYesData         int       `gorm:"column:results_both_teams_score_away_yes_data"`
		ResultsBothTeamsScoreAwayYesPerc         float64   `gorm:"column:results_both_teams_score_away_yes_perc"`
		ResultsBothTeamsScoreHomeNoData          int       `gorm:"column:results_both_teams_score_home_no_data"`
		ResultsBothTeamsScoreHomeNoPerc          float64   `gorm:"column:results_both_teams_score_home_no_perc"`
		ResultsBothTeamsScoreDrawNoData          int       `gorm:"column:results_both_teams_score_draw_no_data"`
		ResultsBothTeamsScoreDrawNoPerc          float64   `gorm:"column:results_both_teams_score_draw_no_perc"`
		ResultsBothTeamsScoreAwayNoData          int       `gorm:"column:results_both_teams_score_away_no_data"`
		ResultsBothTeamsScoreAwayNoPerc          float64   `gorm:"column:results_both_teams_score_away_no_perc"`
		ResultTotalGoalsHomeOver35Data           int       `gorm:"column:result_total_goals_home_over_35_data"`
		ResultTotalGoalsHomeOver35Perc           float64   `gorm:"column:result_total_goals_home_over_35_perc"`
		ResultTotalGoalsDrawOver35Data           int       `gorm:"column:result_total_goals_draw_over_35_data"`
		ResultTotalGoalsDrawOver35Perc           float64   `gorm:"column:result_total_goals_draw_over_35_perc"`
		ResultTotalGoalsAwayOver35Data           int       `gorm:"column:result_total_goals_away_over_35_data"`
		ResultTotalGoalsAwayOver35Perc           float64   `gorm:"column:result_total_goals_away_over_35_perc"`
		ResultTotalGoalsHomeUnder35Data          int       `gorm:"column:result_total_goals_home_under_35_data"`
		ResultTotalGoalsHomeUnder35Perc          float64   `gorm:"column:result_total_goals_home_under_35_perc"`
		ResultTotalGoalsDrawUnder35Data          int       `gorm:"column:result_total_goals_draw_under_35_data"`
		ResultTotalGoalsDrawUnder35Perc          float64   `gorm:"column:result_total_goals_draw_under_35_perc"`
		ResultTotalGoalsAwayUnder35Data          int       `gorm:"column:result_total_goals_away_under_35_data"`
		ResultTotalGoalsAwayUnder35Perc          float64   `gorm:"column:result_total_goals_away_under_35_perc"`
		ResultTotalGoalsHomeOver25Data           int       `gorm:"column:result_total_goals_home_over_25_data"`
		ResultTotalGoalsHomeOver25Perc           float64   `gorm:"column:result_total_goals_home_over_25_perc"`
		ResultTotalGoalsDrawOver25Data           int       `gorm:"column:result_total_goals_draw_over_25_data"`
		ResultTotalGoalsDrawOver25Perc           float64   `gorm:"column:result_total_goals_draw_over_25_perc"`
		ResultTotalGoalsAwayOver25Data           int       `gorm:"column:result_total_goals_away_over_25_data"`
		ResultTotalGoalsAwayOver25Perc           float64   `gorm:"column:result_total_goals_away_over_25_perc"`
		ResultTotalGoalsHomeUnder25Data          int       `gorm:"column:result_total_goals_home_under_25_data"`
		ResultTotalGoalsHomeUnder25Perc          float64   `gorm:"column:result_total_goals_home_under_25_perc"`
		ResultTotalGoalsDrawUnder25Data          int       `gorm:"column:result_total_goals_draw_under_25_data"`
		ResultTotalGoalsDrawUnder25Perc          float64   `gorm:"column:result_total_goals_draw_under_25_perc"`
		ResultTotalGoalsAwayUnder25Data          int       `gorm:"column:result_total_goals_away_under_25_data"`
		ResultTotalGoalsAwayUnder25Perc          float64   `gorm:"column:result_total_goals_away_under_25_perc"`
		GoalsOverunderSecondHalfOver05Data       int       `gorm:"column:goals_overunder__second_half_over_05_data"`
		GoalsOverunderSecondHalfOver05Perc       float64   `gorm:"column:goals_overunder__second_half_over_05_perc"`
		GoalsOverunderSecondHalfUnder05Data      int       `gorm:"column:goals_overunder__second_half_under_05_data"`
		GoalsOverunderSecondHalfUnder05Perc      float64   `gorm:"column:goals_overunder__second_half_under_05_perc"`
		GoalsOverunderSecondHalfOver10Data       int       `gorm:"column:goals_overunder__second_half_over_10_data"`
		GoalsOverunderSecondHalfOver10Perc       float64   `gorm:"column:goals_overunder__second_half_over_10_perc"`
		GoalsOverunderSecondHalfUnder10Data      int       `gorm:"column:goals_overunder__second_half_under_10_data"`
		GoalsOverunderSecondHalfUnder10Perc      float64   `gorm:"column:goals_overunder__second_half_under_10_perc"`
		GoalsOverunderSecondHalfOver15Data       int       `gorm:"column:goals_overunder__second_half_over_15_data"`
		GoalsOverunderSecondHalfOver15Perc       float64   `gorm:"column:goals_overunder__second_half_over_15_perc"`
		GoalsOverunderSecondHalfUnder15Data      int       `gorm:"column:goals_overunder__second_half_under_15_data"`
		GoalsOverunderSecondHalfUnder15Perc      float64   `gorm:"column:goals_overunder__second_half_under_15_perc"`
		GoalsOverunderSecondHalfOver20Data       int       `gorm:"column:goals_overunder__second_half_over_20_data"`
		GoalsOverunderSecondHalfOver20Perc       float64   `gorm:"column:goals_overunder__second_half_over_20_perc"`
		GoalsOverunderSecondHalfUnder20Data      int       `gorm:"column:goals_overunder__second_half_under_20_data"`
		GoalsOverunderSecondHalfUnder20Perc      float64   `gorm:"column:goals_overunder__second_half_under_20_perc"`
		GoalsOverunderSecondHalfOver25Data       int       `gorm:"column:goals_overunder__second_half_over_25_data"`
		GoalsOverunderSecondHalfOver25Perc       float64   `gorm:"column:goals_overunder__second_half_over_25_perc"`
		GoalsOverunderSecondHalfUnder25Data      int       `gorm:"column:goals_overunder__second_half_under_25_data"`
		GoalsOverunderSecondHalfUnder25Perc      float64   `gorm:"column:goals_overunder__second_half_under_25_perc"`
		GoalsOverunderSecondHalfOver30Data       int       `gorm:"column:goals_overunder__second_half_over_30_data"`
		GoalsOverunderSecondHalfOver30Perc       float64   `gorm:"column:goals_overunder__second_half_over_30_perc"`
		GoalsOverunderSecondHalfUnder30Data      int       `gorm:"column:goals_overunder__second_half_under_30_data"`
		GoalsOverunderSecondHalfUnder30Perc      float64   `gorm:"column:goals_overunder__second_half_under_30_perc"`
		GoalsOverunderSecondHalfOver35Data       int       `gorm:"column:goals_overunder__second_half_over_35_data"`
		GoalsOverunderSecondHalfOver35Perc       float64   `gorm:"column:goals_overunder__second_half_over_35_perc"`
		GoalsOverunderSecondHalfUnder35Data      int       `gorm:"column:goals_overunder__second_half_under_35_data"`
		GoalsOverunderSecondHalfUnder35Perc      float64   `gorm:"column:goals_overunder__second_half_under_35_perc"`
		CleanSheetHomeYesData                    int       `gorm:"column:clean_sheet__home_yes_data"`
		CleanSheetHomeYesPerc                    float64   `gorm:"column:clean_sheet__home_yes_perc"`
		CleanSheetHomeNoData                     int       `gorm:"column:clean_sheet__home_no_data"`
		CleanSheetHomeNoPerc                     float64   `gorm:"column:clean_sheet__home_no_perc"`
		CleanSheetAwayYesData                    int       `gorm:"column:clean_sheet__away_yes_data"`
		CleanSheetAwayYesPerc                    float64   `gorm:"column:clean_sheet__away_yes_perc"`
		CleanSheetAwayNoData                     int       `gorm:"column:clean_sheet__away_no_data"`
		CleanSheetAwayNoPerc                     float64   `gorm:"column:clean_sheet__away_no_perc"`
		WinBothHalvesHomeData                    int       `gorm:"column:win_both_halves_home_data"`
		WinBothHalvesHomePerc                    float64   `gorm:"column:win_both_halves_home_perc"`
		WinBothHalvesAwayData                    int       `gorm:"column:win_both_halves_away_data"`
		WinBothHalvesAwayPerc                    float64   `gorm:"column:win_both_halves_away_perc"`
		BothTeamsScoreFirstHalfYesData           int       `gorm:"column:both_teams_score__first_half_yes_data"`
		BothTeamsScoreFirstHalfYesPerc           float64   `gorm:"column:both_teams_score__first_half_yes_perc"`
		BothTeamsScoreFirstHalfNoData            int       `gorm:"column:both_teams_score__first_half_no_data"`
		BothTeamsScoreFirstHalfNoPerc            float64   `gorm:"column:both_teams_score__first_half_no_perc"`
		BothTeamsToScoreSecondHalfYesData        int       `gorm:"column:both_teams_to_score__second_half_yes_data"`
		BothTeamsToScoreSecondHalfYesPerc        float64   `gorm:"column:both_teams_to_score__second_half_yes_perc"`
		BothTeamsToScoreSecondHalfNoData         int       `gorm:"column:both_teams_to_score__second_half_no_data"`
		BothTeamsToScoreSecondHalfNoPerc         float64   `gorm:"column:both_teams_to_score__second_half_no_perc"`
		WinToNilHomeData                         int       `gorm:"column:win_to_nil_home_data"`
		WinToNilHomePerc                         float64   `gorm:"column:win_to_nil_home_perc"`
		WinToNilAwayData                         int       `gorm:"column:win_to_nil_away_data"`
		WinToNilAwayPerc                         float64   `gorm:"column:win_to_nil_away_perc"`
		ExactGoalsNumber0Data                    int       `gorm:"column:exact_goals_number_0_data"`
		ExactGoalsNumber0Perc                    float64   `gorm:"column:exact_goals_number_0_perc"`
		ExactGoalsNumber1Data                    int       `gorm:"column:exact_goals_number_1_data"`
		ExactGoalsNumber1Perc                    float64   `gorm:"column:exact_goals_number_1_perc"`
		ExactGoalsNumber2Data                    int       `gorm:"column:exact_goals_number_2_data"`
		ExactGoalsNumber2Perc                    float64   `gorm:"column:exact_goals_number_2_perc"`
		ExactGoalsNumber3Data                    int       `gorm:"column:exact_goals_number_3_data"`
		ExactGoalsNumber3Perc                    float64   `gorm:"column:exact_goals_number_3_perc"`
		ExactGoalsNumber4Data                    int       `gorm:"column:exact_goals_number_4_data"`
		ExactGoalsNumber4Perc                    float64   `gorm:"column:exact_goals_number_4_perc"`
		ExactGoalsNumber5Data                    int       `gorm:"column:exact_goals_number_5_data"`
		ExactGoalsNumber5Perc                    float64   `gorm:"column:exact_goals_number_5_perc"`
		ExactGoalsNumber6Data                    int       `gorm:"column:exact_goals_number_6_data"`
		ExactGoalsNumber6Perc                    float64   `gorm:"column:exact_goals_number_6_perc"`
		ExactGoalsNumberMore7Data                int       `gorm:"column:exact_goals_number_more_7_data"`
		ExactGoalsNumberMore7Perc                float64   `gorm:"column:exact_goals_number_more_7_perc"`
		ToWinEitherHalfHomeData                  int       `gorm:"column:to_win_either_half_home_data"`
		ToWinEitherHalfHomePerc                  float64   `gorm:"column:to_win_either_half_home_perc"`
		ToWinEitherHalfAwayData                  int       `gorm:"column:to_win_either_half_away_data"`
		ToWinEitherHalfAwayPerc                  float64   `gorm:"column:to_win_either_half_away_perc"`
		HomeTeamExactGoalsNumber0Data            int       `gorm:"column:home_team_exact_goals_number_0_data"`
		HomeTeamExactGoalsNumber0Perc            float64   `gorm:"column:home_team_exact_goals_number_0_perc"`
		HomeTeamExactGoalsNumber1Data            int       `gorm:"column:home_team_exact_goals_number_1_data"`
		HomeTeamExactGoalsNumber1Perc            float64   `gorm:"column:home_team_exact_goals_number_1_perc"`
		HomeTeamExactGoalsNumber2Data            int       `gorm:"column:home_team_exact_goals_number_2_data"`
		HomeTeamExactGoalsNumber2Perc            float64   `gorm:"column:home_team_exact_goals_number_2_perc"`
		HomeTeamExactGoalsNumberMore3Data        int       `gorm:"column:home_team_exact_goals_number_more_3_data"`
		HomeTeamExactGoalsNumberMore3Perc        float64   `gorm:"column:home_team_exact_goals_number_more_3_perc"`
		AwayTeamExactGoalsNumber0Data            int       `gorm:"column:away_team_exact_goals_number_0_data"`
		AwayTeamExactGoalsNumber0Perc            float64   `gorm:"column:away_team_exact_goals_number_0_perc"`
		AwayTeamExactGoalsNumber1Data            int       `gorm:"column:away_team_exact_goals_number_1_data"`
		AwayTeamExactGoalsNumber1Perc            float64   `gorm:"column:away_team_exact_goals_number_1_perc"`
		AwayTeamExactGoalsNumber2Data            int       `gorm:"column:away_team_exact_goals_number_2_data"`
		AwayTeamExactGoalsNumber2Perc            float64   `gorm:"column:away_team_exact_goals_number_2_perc"`
		AwayTeamExactGoalsNumberMore3Data        int       `gorm:"column:away_team_exact_goals_number_more_3_data"`
		AwayTeamExactGoalsNumberMore3Perc        float64   `gorm:"column:away_team_exact_goals_number_more_3_perc"`
		SecondHalfExactGoalsNumber0Data          int       `gorm:"column:second_half_exact_goals_number_0_data"`
		SecondHalfExactGoalsNumber0Perc          float64   `gorm:"column:second_half_exact_goals_number_0_perc"`
		SecondHalfExactGoalsNumber1Data          int       `gorm:"column:second_half_exact_goals_number_1_data"`
		SecondHalfExactGoalsNumber1Perc          float64   `gorm:"column:second_half_exact_goals_number_1_perc"`
		SecondHalfExactGoalsNumber2Data          int       `gorm:"column:second_half_exact_goals_number_2_data"`
		SecondHalfExactGoalsNumber2Perc          float64   `gorm:"column:second_half_exact_goals_number_2_perc"`
		SecondHalfExactGoalsNumber3Data          int       `gorm:"column:second_half_exact_goals_number_3_data"`
		SecondHalfExactGoalsNumber3Perc          float64   `gorm:"column:second_half_exact_goals_number_3_perc"`
		SecondHalfExactGoalsNumber4Data          int       `gorm:"column:second_half_exact_goals_number_4_data"`
		SecondHalfExactGoalsNumber4Perc          float64   `gorm:"column:second_half_exact_goals_number_4_perc"`
		SecondHalfExactGoalsNumberMore5Data      int       `gorm:"column:second_half_exact_goals_number_more_5_data"`
		SecondHalfExactGoalsNumberMore5Perc      float64   `gorm:"column:second_half_exact_goals_number_more_5_perc"`
		ExactGoalsNumberFirstHalf0Data           int       `gorm:"column:exact_goals_number__first_half_0_data"`
		ExactGoalsNumberFirstHalf0Perc           float64   `gorm:"column:exact_goals_number__first_half_0_perc"`
		ExactGoalsNumberFirstHalf1Data           int       `gorm:"column:exact_goals_number__first_half_1_data"`
		ExactGoalsNumberFirstHalf1Perc           float64   `gorm:"column:exact_goals_number__first_half_1_perc"`
		ExactGoalsNumberFirstHalf2Data           int       `gorm:"column:exact_goals_number__first_half_2_data"`
		ExactGoalsNumberFirstHalf2Perc           float64   `gorm:"column:exact_goals_number__first_half_2_perc"`
		ExactGoalsNumberFirstHalf3Data           int       `gorm:"column:exact_goals_number__first_half_3_data"`
		ExactGoalsNumberFirstHalf3Perc           float64   `gorm:"column:exact_goals_number__first_half_3_perc"`
		ExactGoalsNumberFirstHalf4Data           int       `gorm:"column:exact_goals_number__first_half_4_data"`
		ExactGoalsNumberFirstHalf4Perc           float64   `gorm:"column:exact_goals_number__first_half_4_perc"`
		ExactGoalsNumberFirstHalfMore5Data       int       `gorm:"column:exact_goals_number__first_half_more_5_data"`
		ExactGoalsNumberFirstHalfMore5Perc       float64   `gorm:"column:exact_goals_number__first_half_more_5_perc"`
		ToScoreInBothHalvesByTeamsHomeData       int       `gorm:"column:to_score_in_both_halves_by_teams_home_data"`
		ToScoreInBothHalvesByTeamsHomePerc       float64   `gorm:"column:to_score_in_both_halves_by_teams_home_perc"`
		ToScoreInBothHalvesByTeamsAwayData       int       `gorm:"column:to_score_in_both_halves_by_teams_away_data"`
		ToScoreInBothHalvesByTeamsAwayPerc       float64   `gorm:"column:to_score_in_both_halves_by_teams_away_perc"`
		TotalGoalsBothTeamsToScoreOverYes25Data  int       `gorm:"column:total_goals_both_teams_to_score_over_yes_25_data"`
		TotalGoalsBothTeamsToScoreOverYes25Perc  float64   `gorm:"column:total_goals_both_teams_to_score_over_yes_25_perc"`
		TotalGoalsBothTeamsToScoreOverNo25Data   int       `gorm:"column:total_goals_both_teams_to_score_over_no_25_data"`
		TotalGoalsBothTeamsToScoreOverNo25Perc   float64   `gorm:"column:total_goals_both_teams_to_score_over_no_25_perc"`
		TotalGoalsBothTeamsToScoreUnderYes25Data int       `gorm:"column:total_goals_both_teams_to_score_under_yes_25_data"`
		TotalGoalsBothTeamsToScoreUnderYes25Perc float64   `gorm:"column:total_goals_both_teams_to_score_under_yes_25_perc"`
		TotalGoalsBothTeamsToScoreUnderNo25Data  int       `gorm:"column:total_goals_both_teams_to_score_under_no_25_data"`
		TotalGoalsBothTeamsToScoreUnderNo25Perc  float64   `gorm:"column:total_goals_both_teams_to_score_under_no_25_perc"`
		HalftimeResultBothTeamsScoreHomeYesData  int       `gorm:"column:halftime_result_both_teams_score_home_yes_data"`
		HalftimeResultBothTeamsScoreHomeYesPerc  float64   `gorm:"column:halftime_result_both_teams_score_home_yes_perc"`
		HalftimeResultBothTeamsScoreDrawYesData  int       `gorm:"column:halftime_result_both_teams_score_draw_yes_data"`
		HalftimeResultBothTeamsScoreDrawYesPerc  float64   `gorm:"column:halftime_result_both_teams_score_draw_yes_perc"`
		HalftimeResultBothTeamsScoreAwayYesData  int       `gorm:"column:halftime_result_both_teams_score_away_yes_data"`
		HalftimeResultBothTeamsScoreAwayYesPerc  float64   `gorm:"column:halftime_result_both_teams_score_away_yes_perc"`
		HalftimeResultBothTeamsScoreHomeNoData   int       `gorm:"column:halftime_result_both_teams_score_home_no_data"`
		HalftimeResultBothTeamsScoreHomeNoPerc   float64   `gorm:"column:halftime_result_both_teams_score_home_no_perc"`
		HalftimeResultBothTeamsScoreDrawNoData   int       `gorm:"column:halftime_result_both_teams_score_draw_no_data"`
		HalftimeResultBothTeamsScoreDrawNoPerc   float64   `gorm:"column:halftime_result_both_teams_score_draw_no_perc"`
		HalftimeResultBothTeamsScoreAwayNoData   int       `gorm:"column:halftime_result_both_teams_score_away_no_data"`
		HalftimeResultBothTeamsScoreAwayNoPerc   float64   `gorm:"column:halftime_result_both_teams_score_away_no_perc"`
		BothTeamsToScore1StHalf2NdHalfYesYesData int       `gorm:"column:both_teams_to_score_1st_half__2nd_half_yes_yes_data"`
		BothTeamsToScore1StHalf2NdHalfYesYesPerc float64   `gorm:"column:both_teams_to_score_1st_half__2nd_half_yes_yes_perc"`
		BothTeamsToScore1StHalf2NdHalfYesNoData  int       `gorm:"column:both_teams_to_score_1st_half__2nd_half_yes_no_data"`
		BothTeamsToScore1StHalf2NdHalfYesNoPerc  float64   `gorm:"column:both_teams_to_score_1st_half__2nd_half_yes_no_perc"`
		BothTeamsToScore1StHalf2NdHalfNoYesData  int       `gorm:"column:both_teams_to_score_1st_half__2nd_half_no_yes_data"`
		BothTeamsToScore1StHalf2NdHalfNoYesPerc  float64   `gorm:"column:both_teams_to_score_1st_half__2nd_half_no_yes_perc"`
		BothTeamsToScore1StHalf2NdHalfNoNoData   int       `gorm:"column:both_teams_to_score_1st_half__2nd_half_no_no_data"`
		BothTeamsToScore1StHalf2NdHalfNoNoPerc   float64   `gorm:"column:both_teams_to_score_1st_half__2nd_half_no_no_perc"`
		TotalGoalsUnder2Data                     int       `gorm:"column:total_goals_under_2_data"`
		TotalGoalsUnder2Perc                     float64   `gorm:"column:total_goals_under_2_perc"`
		TotalGoals2Or3Data                       int       `gorm:"column:total_goals_2_or_3_data"`
		TotalGoals2Or3Perc                       float64   `gorm:"column:total_goals_2_or_3_perc"`
		TotalGoalsOver3Data                      int       `gorm:"column:total_goals_over_3_data"`
		TotalGoalsOver3Perc                      float64   `gorm:"column:total_goals_over_3_perc"`
		CreatedAt                                time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;NOT NULL"`
		UpdatedAt                                time.Time `gorm:"column:updated_at"`
		DeletedAt                                time.Time `gorm:"column:deleted_at"`
 
		LeagueapiID                              int       `gorm:"column:leagueapi_id"`
		TotalFixtures                            int       `gorm:"column:total_fixtures"`
		PreAhPattern                             string    `gorm:"column:pre_ah_pattern"`
		PreGouPattern                            string    `gorm:"column:pre_gou_pattern"`
		EndAhPattern                             string    `gorm:"column:end_ah_pattern"`
		EndGouPattern                            string    `gorm:"column:end_gou_pattern"`
	}

	func (m *FootballPatternFromCountry) TableName() string {
		return "football_pattern_from_country"
	}

	func (b *FootballPatternFromCountry) GetPatternFromCountry(leagueapiID uint, preAhPattern, preGouPattern, endAhPattern, endGouPattern string) ([]FootballPatternFromCountry, error) {
		var footballpatternfromcountry []FootballPatternFromCountry
	
		err := database.DB.
			Select("*").
			Where("leagueapi_id = ?", leagueapiID).
			Where("pre_ah_pattern LIKE ?", preAhPattern).
			Where("pre_gou_pattern LIKE ?", preGouPattern).
			Where("end_ah_pattern LIKE ?", endAhPattern).
			Where("end_gou_pattern LIKE ?", endGouPattern).
			Find(&footballpatternfromcountry).Error
	
		return footballpatternfromcountry, err
	}

	// func (b *FootballPatternFromCountry) GetPatternFrom(leagueapiID uint, preAhPattern, preGouPattern, endAhPattern, endGouPattern string) (FootballPatternFromCountry, error) {
	// 	var footballpatternfromcountry FootballPatternFromCountry
	
	// 	err := database.DB.
	// 		Select("*").
	// 		Where("leagueapi_id = ?", leagueapiID).
	// 		Where("pre_ah_pattern LIKE ?", preAhPattern).
	// 		Where("pre_gou_pattern LIKE ?", preGouPattern).
	// 		Where("end_ah_pattern LIKE ?", endAhPattern).
	// 		Where("end_gou_pattern LIKE ?", endGouPattern).
	// 		First(&footballpatternfromcountry).Error
	
	// 	return footballpatternfromcountry, err
	// }
	
	